### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'stock_daliy/000416.txt'

### ISSUE THREAD

**Issue by SeekPoint** [DemonDamon/FinnewsHunter#1]
(.venv) ub16hp@UB16HP:~/ub16_prj/Listed-company-news-crawl-and-text-analysis$ python3 run_crawler_tushare.py
Traceback (most recent call last):
  File "run_crawler_tushare.py", line 13, in <module>
    Obj.getStockDayHistory('Stock',stockcode)
  File "/home/ub16hp/ub16_prj/Listed-company-news-crawl-and-text-analysis/Crawler/crawler_tushare.py", line 90, in getStockDayHistory
    for row in open(Path,'r'):
FileNotFoundError: [Errno 2] No such file or directory: 'stock_daliy/000416.txt'
(.venv) ub16hp@UB16HP:~/ub16_prj/Listed-company-news-crawl-and-text-analysis$

**Comment by panwenlei** [comment]
I encountered the same problem...how to handle it ?

**Comment by DemonDamon** [comment]
> I encountered the same problem...how to handle it ?

i think is the crawling issues. is the .txt file of that stock daily price in stock_daily file?

**Comment by MoonMoon-He** [comment]
where is stock_daily file? I can't find it. hope u response asap thanks
